server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**,/api/auth/**
        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/api/restaurants/**,/api/categories/**,/api/menu/**,/api/tables/**
        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/api/reservations/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/cart/**,/api/orders/**,/api/kitchen/orders/**
        - id: billing-service
          uri: lb://BILLING-SERVICE
          predicates:
            - Path=/api/payments/**,/api/invoices/**

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
