server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: reservation-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://dinepilot:dinepilot@localhost:27017/reservation_db?authSource=admin}

jwt:
  secret: ${JWT_SECRET:HZ+XCLqA5NGg9IezhLOdOOqv2PUf1PB7fgMii0y/gR7stKUJ/24qBexjk5XC44Wd-dev-only}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
